export { default as CpuCard } from './components/CpuCard.jsx'
export { default as RamCard } from './components/RamCard.jsx'
export { default as GpuCard } from './components/GpuCard.jsx'
export { default as NetworkCard } from './components/NetworkCard.jsx'
export { default as DiskCard } from './components/DiskCard.jsx'